### ISSUE TITLE
Couldn't resolve archetype

### ISSUE THREAD

**Issue by alanrecine** [kolorobot/spring-mvc-quickstart-archetype#59]
Well, every time i tried to create a new maven project, i get the same error.

http://puu.sh/9m6Tu/233b9bf57b.png 

Creating spring-mvc-quickstart has encountered a problem.

Could not resolve archetype...... from any of the configured repositories.

What should i do?

**Comment by chapita** [comment]
Hi @Kolorobot, I used to have the same prolem as @alucabj afer a lot of attempts, I realized the problem was when i select the archetype-catalog.xml file instead of select the one in the clone folder y should select the one in the .m2 repository after the mvn clean install, I did that and the archetype c reation from STS for fine for me. Thanks for this amazing archetype.
